### ISSUE TITLE
make后build.sh文件报错，看了一下不是中英文符合问题，望解答

### ISSUE THREAD

**Issue by wqshan001** [xuperchain/xbench#39]
root@wqs-virtual-machine:/home/wqs# cd xbench/
root@wqs-virtual-machine:/home/wqs/xbench# make
sh script/build.sh
script/build.sh: 10: Syntax error: "(" unexpected
make: *** [Makefile:4：build] 错误 2

**Comment by wqshan001** [comment]
问题以解决
参考博客https://blog.csdn.net/qq_39816087/article/details/101844899

**Comment by Greenyw** [comment]
您好，我是汪怡青 您的邮件已经收到。我会尽快给您回复！
